"""
Django settings for ecommerce project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import importlib.util
import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load BASE_DIR/.env into the environment before anything reads os.environ.
# Real environment variables always win, so a systemd unit or a `export` in the
# shell overrides the file rather than the other way round — production sets
# secrets properly and never needs a .env on disk.
try:
    from dotenv import load_dotenv
except ImportError:
    # python-dotenv is optional: without it, only real env vars are used.
    pass
else:
    load_dotenv(BASE_DIR / '.env', override=False)


def _env_bool(name, default):
    return os.environ.get(name, str(default)).strip().lower() in ('1', 'true', 'yes', 'on')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# In production set DJANGO_SECRET_KEY in the environment (see README).
# This fallback exists so a fresh clone runs without setup. It is committed, so
# it is public knowledge — the guard below stops it reaching production.
INSECURE_SECRET_KEY = 'django-insecure-b=)*#6-kxqv#t#y56=&c(*ur^^s)cc4nstnjv%3q_h5ez(2(vm'
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', INSECURE_SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to True for local development; set DJANGO_DEBUG=False on the server.
DEBUG = _env_bool('DJANGO_DEBUG', True)

# Refuse to boot rather than silently serving with a signing key anyone can read
# from the repository: SECRET_KEY signs session cookies, so a known one lets an
# attacker mint a session for any account, including staff.
if not DEBUG and SECRET_KEY == INSECURE_SECRET_KEY:
    raise ImproperlyConfigured(
        'DJANGO_SECRET_KEY must be set when DEBUG is off. The fallback key is '
        'published in this repository and cannot be used in production. '
        'Generate one with: python -c '
        '"from django.core.management.utils import get_random_secret_key as k; print(k())"'
    )

# Comma-separated list, e.g. DJANGO_ALLOWED_HOSTS="ironhold.example,www.ironhold.example"
ALLOWED_HOSTS = [h.strip() for h in os.environ.get(
    'DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()]

# Needed for HTTPS POSTs (login, language switch) behind a proxy.
# e.g. DJANGO_CSRF_TRUSTED_ORIGINS="https://ironhold.example,https://www.ironhold.example"
CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.environ.get(
    'DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # intcomma / naturaltime, used by the clinic dashboard templates.
    'django.contrib.humanize',
    'store',
]

# The `clinic` back office is an optional add-on: it reads store data to draw
# the finance and inventory dashboard, and nothing in `store` imports it. Delete
# the clinic/ directory and the site keeps working — this probe is what makes
# that true, since a missing app named in INSTALLED_APPS is a startup error.
CLINIC_INSTALLED = importlib.util.find_spec('clinic') is not None
if CLINIC_INSTALLED:
    INSTALLED_APPS.append('clinic')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise serves static files in production; harmless in development.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecommerce.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# Spanish is the source language: the strings written inside {% trans %} in the
# templates are Spanish, so 'es' needs no catalog — msgids pass through as-is.
# English is provided by translating those msgids in locale/en/.
LANGUAGE_CODE = 'es'

LANGUAGES = [
    ('es', 'Español'),
    ('en', 'English'),
]

LOCALE_PATHS = [BASE_DIR / 'locale']

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# `collectstatic` gathers everything here for the server to serve.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# In production, let WhiteNoise compress + fingerprint static files.
# Left as the default in DEBUG so runserver/admin work without collectstatic.
if not DEBUG:
    STORAGES = {
        'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
        'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'},
    }

# Media files (user-uploaded content, e.g. product images)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# --- Stripe ---
# Keys come from the Stripe dashboard (Developers → API keys). Test keys start
# with pk_test_ / sk_test_; live keys with pk_live_ / sk_live_.
# Never commit a secret key — set these in the environment (see README).
STRIPE_PUBLISHABLE_KEY = os.environ.get('STRIPE_PUBLISHABLE_KEY', '')
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY', '')
# From `stripe listen` locally, or the webhook endpoint's signing secret in the
# dashboard. Without it, incoming webhooks cannot be verified and are rejected.
STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET', '')
# ISO currency code. Change to 'mxn', 'eur', etc. to match your Stripe account.
STRIPE_CURRENCY = os.environ.get('STRIPE_CURRENCY', 'usd').lower()

# When no secret key is configured the store falls back to recording orders
# directly, so the site stays demoable before Stripe is wired up.
STRIPE_ENABLED = bool(STRIPE_SECRET_KEY)


# --- Security hardening (only enforced when DEBUG is off) ---
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = _env_bool('DJANGO_SECURE_SSL_REDIRECT', True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 30  # 30 days
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
