# Generated by Django 6.0.6 on 2026-06-13 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad')),
                ('occupation', models.CharField(blank=True, max_length=120, verbose_name='Ocupacion')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Celular')),
                ('diabetic', models.BooleanField(default=False, verbose_name='Diabetes')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente / Paciente',
                'verbose_name_plural': 'Clientes / Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('role', models.CharField(choices=[('podologa', 'Podologa'), ('cosmetologa', 'Cosmetologa'), ('masajista', 'Masajista'), ('admin', 'Administracion')], default='podologa', max_length=20, verbose_name='Puesto')),
                ('base_salary_weekly', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sueldo base semanal')),
                ('commission_rate', models.DecimalField(decimal_places=4, default=0, help_text='Fraccion del servicio que se paga como comision (ej. 0.0862)', max_digits=6, verbose_name='Tasa de comision')),
                ('active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Empleada',
                'verbose_name_plural': 'Empleadas',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('category', models.CharField(choices=[('rent', 'Renta'), ('salary', 'Salarios'), ('utilities', 'Servicios (luz, agua, internet)'), ('tax', 'SAT / Contador'), ('supplies', 'Compras / Insumos'), ('other', 'Otro')], max_length=15, verbose_name='Categoria')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Nota')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Producto')),
                ('for_sale', models.BooleanField(default=True, help_text='Si = se vende al cliente. No = insumo de uso interno.', verbose_name='Es para venta')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo unitario')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio de venta')),
                ('stock', models.IntegerField(default=0, verbose_name='Existencia')),
            ],
            options={
                'verbose_name': 'Producto / Insumo',
                'verbose_name_plural': 'Productos / Insumos',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Servicio')),
                ('category', models.CharField(choices=[('podologia', 'Podologia'), ('facial', 'Facial / Cosmetologia'), ('masaje', 'Masaje'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Categoria')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio de lista')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de servicio',
                'verbose_name_plural': 'Tipos de servicio',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('kind', models.CharField(choices=[('service', 'Servicio'), ('product_sale', 'Venta de producto'), ('product_use', 'Uso de insumo'), ('tip', 'Propina')], max_length=15, verbose_name='Tipo')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto')),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta'), ('transfer', 'Transferencia'), ('na', 'N/A')], default='na', max_length=10, verbose_name='Pago')),
                ('walk_in', models.BooleanField(default=False, help_text='El cliente llego sin cita previa.', verbose_name='Sin cita')),
                ('is_imported_aggregate', models.BooleanField(default=False, verbose_name='Importado del Excel')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Nota')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.client', verbose_name='Cliente')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='clinic.employee', verbose_name='Atendio')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.product', verbose_name='Producto')),
                ('service_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.servicetype', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'indexes': [models.Index(fields=['date', 'kind'], name='clinic_tran_date_c14637_idx')],
            },
        ),
    ]
