# Generated by Django 5.2.16 on 2026-07-27 03:54

import django.db.models.deletion
from django.db import migrations, models


def clear_stale_product_links(apps, schema_editor):
    """Drop references to the old clinic.Product table before repointing.

    Transaction.product used to hold clinic.Product ids. The AlterField below
    reinterprets that same column as store.Products ids — the numbers would
    survive and quietly point at unrelated products. Nulling them first turns
    a silent mis-attribution into an obvious blank that can be re-linked by
    hand. The amounts are untouched, so no revenue figure moves.
    """
    Transaction = apps.get_model('clinic', 'Transaction')
    Transaction.objects.filter(product__isnull=False).update(product=None)


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0001_initial"),
        ("store", "0005_product_inventory_and_decimal_money"),
    ]

    operations = [
        migrations.RunPython(clear_stale_product_links,
                             migrations.RunPython.noop),
        migrations.AlterField(
            model_name="transaction",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.products",
                verbose_name="Producto",
            ),
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
