# Generated by Django 6.0.6 on 2026-07-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_shipped_at_order_tracking_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='customer',
            name='address_line2',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Apt / suite / unit'),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, default='United States', max_length=60),
        ),
        migrations.AddField(
            model_name='customer',
            name='recipient_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Recipient'),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='State / province'),
        ),
        migrations.AddField(
            model_name='customer',
            name='street_address',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Street address'),
        ),
        migrations.AddField(
            model_name='customer',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=12, verbose_name='ZIP / postal code'),
        ),
        migrations.AddField(
            model_name='order',
            name='address_line2',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Apt / suite / unit'),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(blank=True, default='United States', max_length=60),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Recipient'),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='State / province'),
        ),
        migrations.AddField(
            model_name='order',
            name='street_address',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Street address'),
        ),
        migrations.AddField(
            model_name='order',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=12, verbose_name='ZIP / postal code'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
