# Generated by Django 5.2.16 on 2026-07-27 03:49

from decimal import Decimal
from django.db import migrations, models


def grandfather_existing_products(apps, schema_editor):
    """Leave the pre-existing catalogue sellable.

    `track_inventory` defaults to True and `stock` to 0, so without this every
    product already in the database would become unbuyable the moment this
    migration ran. Rows that exist now predate stock control, so they opt out
    of it; anything created afterwards gets the default and is tracked. Set a
    real stock count and tick "track inventory" per product when you are ready.
    """
    Products = apps.get_model('store', 'Products')
    Products.objects.update(track_inventory=False)


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_order_paid_at_order_payment_status_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="products",
            options={"verbose_name_plural": "Products"},
        ),
        migrations.AddField(
            model_name="products",
            name="for_sale",
            field=models.BooleanField(
                default=True, help_text="Show this item in the storefront."
            ),
        ),
        migrations.AddField(
            model_name="products",
            name="stock",
            field=models.PositiveIntegerField(
                default=0, help_text="Units on hand. Decremented when payment clears."
            ),
        ),
        migrations.AddField(
            model_name="products",
            name="track_inventory",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck to sell this item without stock limits.",
            ),
        ),
        migrations.AddField(
            model_name="products",
            name="unit_cost",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.RunPython(grandfather_existing_products,
                             migrations.RunPython.noop),
    ]
